[package]
name = "mawallet"
version = "1.56.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["v4"] }
rand = "0.8.4"
nine = "0.5.0"
sha2 = "0.10.2"
ring = "0.16.20"
